version: '3.9'
services:
  phonebook:
    build: .
    container_name: yealink-phonebook
    environment:
      - APP_PORT=5000
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-admin}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-admin}
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
