version: '3.9'
services:
  phonebook:
    build: .
    container_name: yealink-phonebook
    environment:
      - APP_PORT=5000
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-admin}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-admin}
    ports:
      - "5000:5000"
    volumes:
      # Замените /var/www/html на каталог веб-сервера, если он отличается
      - /var/www/html:/app/data
      - ./static/photos:/app/static/photos
    restart: unless-stopped
